# Generated by Django 3.0.2 on 2020-07-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200726_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
